#!/usr/bin/env zsh

target=$1
: ${target:=.}

statusflags=$2

find $target -name .git -type d | while read filename
do
  flags="--git-dir=$filename --work-tree=${filename:h}"
  ahead=$(git ${=flags} status | grep '^Your branch is ahead')
  dirty=$(git ${=flags} status --short $statusflags | sed 's/^/  /')

  if [[ -n $dirty || -n $ahead ]]; then
    echo ${filename:h}

    if [[ -n $ahead ]]; then
      echo "  \e[36;1m$ahead\e[0m"
    fi

    if [[ -n $dirty ]]; then
      echo "\e[30;1m$dirty\e[0m"
    fi
  fi
done

return 0
